services:
  ros2-jazzy:
    build: .
    container_name: ros2_jazzy_container
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ./workspace:/ros2_ws
    devices:
      - /dev/dri:/dev/dri # Hardware acceleration for Intel / AMD GPUs
    ipc: host
    network_mode: host
    stdin_open: true
    tty: true
